AWSTemplateFormatVersion: 2010-09-09
Description: Stealth Store Lambda functions

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  reservations:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/reservations.reservationsHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Manage reservations at the Stealth Store.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: stealth-store-reservations
      Environment:
        Variables:
          RESERVATIONS_TABLE: stealth-store-reservations

  services:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/services.servicesHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Define all available services offered at the Stealth Store.
